### ISSUE TITLE
toNumberPreprocessor converts empty string to 0

### ISSUE THREAD

**Issue by Gambitier** [lokalise/zod-extras#40]
javascript converts empty string to 0. So if the this preprocessor is applied for number and if input is empty string then after transformation we receive value 0 which is number and hence zod doesn't throw any error

```js
console.log(+''); // 0
```

https://github.com/lokalise/zod-extras/blob/cbe209bc259871b0476c93ffea14443c59fd6ebe/src/utils/toNumberPreprocessor.ts#L6-L8

**Comment by lokankr** [comment]
Thank you for the report! This has been fixed and `v2.0.0` has been released.
